TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sitegeist.Monocle': TRUE
    modules:
      administration:
        submodules:
          monocle:
            label: 'Monocle'
            controller: '\Sitegeist\Monocle\Controller\StyleguideController'
            description: 'A Styleguide implementation based on TypoScript prototypes and the idea of atomic-design'
            icon: 'icon-magic'
            privilegeTarget: 'Sitegeist.Monocle:Backend.Styleguide'
            additionalResources:
              styleSheets:
                module: 'resource://Sitegeist.Monocle/Public/Styles/Module.css'
                app: 'resource://Sitegeist.Monocle/Public/Styles/App.css'
              javaScripts:
                app: 'resource://Sitegeist.Monocle/Public/JavaScript/App.js'


Sitegeist:
  Monocle:

    breakpoints:
      xs:
        label: 'xtra small'
        width: 400
      md:
        label: 'medium'
        width: 600
      wide:
        label: 'wide'
        width: 800

    preview:
      defaultPath: 'atoms'
      additionalResources:
        styleSheets:
          # example:  'resource://Vendor.Site/Public/Styles/Main.css'
        javaScripts:
          # example: 'resource://Vendor.Site/Public/Scripts/Main.js'
