
Sitegeist:
  Monocle:
    packages: {  }

    ui:
      hotkeys:
        openNavigation: 'ctrl+f'
        closeNavigation: 'esc'
        navigateUp: 'up'
        navigateDown: 'down'
        openPreviewInNewWindow: 'ctrl+space'

      localePresets:
        de:
          label: 'German'
          fallback: ['de', 'en']
        en:
          label: 'English'
          fallback: ['en_UK', 'en']
        fr:
          label: 'French'

      viewportPresets:
        xs:
          label: 'xtra small'
          width: 400
          height: 600
        md:
          label: 'medium'
          width: 600
          height: 400
        l:
          label: 'wide'
          width: 800
          height: 600

      structure:
        base:
          position: 100
          match: Components?\.Base
          label: Base
          icon: icon-minus
          color: '#AAA'
        atoms:
          position: 200
          match: Components?\.Atom
          label: Atoms
          icon: icon-gear
          color: '#4DBCE9'
        molecules:
          position: 300
          match: Components?\.Molecule
          label: Molecules
          icon: icon-gears
          color: '#26ADE4'
        organisms:
          position: 400
          match: Components?\.Organism
          label: Organisms
          icon: icon-certificate
          color: '#D1E751'
        templates:
          position: 500
          match: Components?\.Template
          label: Templates
          icon: icon-file
          color: '#FFF'

    preview:
      fusionRootPath: '/<Sitegeist.Monocle:Preview.Page>'
      sourceQuerySelector: 'body'
      # defaultPrototypeName: 'Vendor.Site:Prototype'

Neos:
  Flow:
    mvc:
      routes:
        'Sitegeist.Monocle':
          position: 'before Neos.Neos'
    security:
      authentication:
        providers:
          Neos.Neos:Backend:
            requestPatterns:
              'Sitegeist.Monocle:monocleControllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\Monocle\Controller\.*'
  Neos:
    fusion:
      autoInclude:
        Sitegeist.Monocle: true

    modules:
      administration:
        submodules:
          monocle:
            label: Monocle
            controller: \Sitegeist\Monocle\Controller\StyleguideController
            description: 'A styleguide for fusion prototypes and the idea of components'
            icon: icon-magic
            privilegeTarget: 'Sitegeist.Monocle:Backend.Styleguide'
            additionalResources:
              styleSheets:
                module: 'resource://Sitegeist.Monocle/Public/Styles/Module.css'

