TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Sitegeist.Monocle': TRUE
    modules:
      administration:
        submodules:
          monocle:
            label: 'Monocle'
            controller: '\Sitegeist\Monocle\Controller\StyleguideController'
            description: 'A Styleguide implementation based on TypoScript prototypes and the idea of atomic-design'
            icon: 'icon-magic'
            privilegeTarget: 'Sitegeist.Monocle:Backend.Styleguide'
            additionalResources:
              styleSheets:
                module: 'resource://Sitegeist.Monocle/Public/Styles/Module.css'

  Flow:
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              'Sitegeist.Monocle:monocleControllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Sitegeist\Monocle\Controller\.*'

Sitegeist:
  Monocle:

    viewportPresets: []
#    viewportPresets:
#      xs:
#        label: 'xtra small'
#        width: 400
#        height: 600
#      md:
#        label: 'medium'
#        width: 600
#        height: 400
#      l:
#        label: 'wide'
#        width: 800
#        height: 600

    preview:
      defaultPath: 'atoms.basic'
      additionalResources:
        styleSheets: []
          # example:  'resource://Vendor.Site/Public/Styles/Main.css'
        javaScripts: []
          # example: 'resource://Vendor.Site/Public/Scripts/Main.js'
